<?php

$lang = array(
	'__app_gw2integration'	=> "GW2 Integration",
	'profile_gw2integration_gw2integration'	=> "GW2 Integration",
    'member__gw2integration_gw2integration' => "GW2 Integration",
	'gw2_api_key'	=> "GuildWars 2 API Key",
	'manage_api_key'	=> "Manage API Key",
    'guilds' => "Guilds",
	'privacy_settings'	=> "Privacy Settings",
	'general'	=> "General",
	'pvp'	=> "PvP",
    'represent_guild' => "Represent Guild",
	'display_account_name'	=> "Display Account Name",
	'display_world'	=> "Display World",
	'display_played_since'	=> "Display Played Since",
	'display_playtime'	=> "Display Playtime",
	'display_ap'	=> "Display Achievement Points",
	'display_fractal_level'	=> "Display Fractal Level",
	'display_wvw_rank'	=> "Display WvW Rank",
	'display_commander'	=> "Display Commander",
	'display_guilds'	=> "Display Guilds",
	'display_game_version'	=> "Display Game Version",
	'display_characters'	=> "Display Characters",
	'display_pvp_rank'	=> "Display PvP Rank",
	'display_pvp_stats'	=> "Display PvP Stats",
	'display_pvp_profession_stats'	=> "Display PvP Profession Stats",
	'display_pvp_seasons'	=> "Display PvP Seasons",
	'display_pvp_games'	=> "Display PvP Games",
    'display_pvp_game_played_with' => "Display Game Played With"
);
