<ips:template parameters="$form, $messages" />
<div data-controller="gw2integration.front.gw2.profilesettingssave">
    <h2 class="ipsType_sectionHead">Guild Wars 2 Integration Settings</h2>
    <hr class="ipsHr">
    {{foreach $messages as $message}}
    <div style="white-space: pre-line" class="ipsMessage {$message["type"] == 0 ? 'ipsMessage_success' : 'ipsMessage_error'}">{$message["text"]}</div>
    {{endforeach}}
    {$form|raw}
</div>