<ips:template parameters="$tab" />
<li>
    <a href='{url="app=core&module=system&controller=settings&area=gw2integration" seoTemplate="settings_gw2integration"}' id='setting_gw2integration' class='ipsType_normal ipsSideMenu_item {{if $tab === "gw2integration"}}ipsSideMenu_itemActive{{endif}}'title="GW2 Integration" role="tab" aria-selected="true">
        <img src="{resource='img/gw2_icon.png'}" style="width: 30px;padding: 4px;"> GW2 Integration 
    </a>
</li>